JExamXML is now used instead of diff utility. Tests have been updated & fixed.

diff --git a/tests/initial/#00: Environment/cmd-given b/tests/initial/#00: Environment/cmd-given
--- a/tests/initial/#00: Environment/cmd-given
+++ b/tests/initial/#00: Environment/cmd-given
@@ -20,7 +20,6 @@ if [[ "$(hostname)" == "merlin.fit.vutbr.cz" ]]; then
   }
 
   for file_path in $(find . -type f -name cmd-given | sort); do
-    
     # Changing 'cmd-given' scripts, so they can run on merlin server:
     {
       sed -i -r -e 's/php "\$ROOT_PATH"\/jsn\.php/php -d open_basedir="" "\$ROOT_PATH"\/jsn.php/g' "$file_path"
@@ -38,10 +37,18 @@ else
   fi
 fi
 
-if [[ -r "$ROOT_PATH/jsn.php" && -f "$ROOT_PATH/jsn.php" && -s "$ROOT_PATH/jsn.php" ]]; then
-  echo "OK"
-  exit 0
-else
-  echo "The 'jsn.php' is not present in '\$ROOT_PATH' or is not readable!"
+"$ROOT_PATH"/jexamxml.sh "$(pwd)" "" ""
+
+if [[ $? != 2 ]]; then
+  echo "The Java CLI is either missing or JExamXML files are corrupted!"
   exit 5
 fi
+
+if ! [[ -r "$ROOT_PATH/jsn.php" && -f "$ROOT_PATH/jsn.php" && -s "$ROOT_PATH/jsn.php" ]]; then
+  echo "The 'jsn.php' is not present in '\$ROOT_PATH' or is not readable!"
+  exit 6
+fi
+
+echo "OK"
+
+exit 0
diff --git a/tests/parameters/#15: -h= (default substitution)/cmd-given b/tests/parameters/#15: -h= (default substitution)/cmd-given
--- a/tests/parameters/#15: -h= (default substitution)/cmd-given
+++ b/tests/parameters/#15: -h= (default substitution)/cmd-given
@@ -1,2 +1,36 @@
 #!/bin/bash
-php "$ROOT_PATH"/jsn.php < "$ROOT_PATH"/subst-file
+php "$ROOT_PATH"/jsn.php < "$ROOT_PATH"/subst-file > script-output
+
+RET_VAL=$?
+
+cat "$ROOT_PATH"/XML-header > valid-output
+
+echo "<root>
+<first-Name value=\"Tomáš\" />
+</root>" >> valid-output
+
+if [[ $RET_VAL -gt 0 ]]; then
+  echo "The script should process this input without any error!"
+else
+  # NOTE: We're injecting <root> & </root> elements so the JExamXML will not
+  #       report an error that the XML is not well-formed.
+  cat "$ROOT_PATH"/XML-header > script-output.tmp
+  echo "<root>" >> script-output.tmp
+  tail -n +2 script-output >> script-output.tmp
+  cat script-output.tmp > script-output
+  echo "</root>" >> script-output
+  
+  rm -f script-output.tmp
+  
+  "$ROOT_PATH"/jexamxml.sh "$(pwd)" valid-output script-output
+
+  if [[ $? != 0 ]]; then
+    echo "Wrong output format for default substitution! See the delta.xml file."
+  else
+    rm -f valid-output script-output delta.xml
+    echo "OK"
+  fi
+fi
+
+exit $RET_VAL
+
diff --git a/tests/parameters/#34: -c (off)/cmd-given b/tests/parameters/#34: -c (off)/cmd-given
--- a/tests/parameters/#34: -c (off)/cmd-given
+++ b/tests/parameters/#34: -c (off)/cmd-given
@@ -1,2 +1,28 @@
 #!/bin/bash
-php "$ROOT_PATH"/jsn.php < "$ROOT_PATH"/problematic-characters
+php "$ROOT_PATH"/jsn.php < "$ROOT_PATH"/problematic-characters | tr -d '\n' > script-output
+
+RET_VAL=$?
+
+echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
+<test1 value=\"<\"Dee'Kej!\">\" />
+<test2>
+    <array>
+        <item value=\"<\"Dee'Kej!\">\" />
+    </array>
+</test2>" | tr -d '\n' > valid-output
+
+if [[ $RET_VAL -gt 0 ]]; then
+  echo "The script should process this input without any error!"
+else
+  diff -upwB valid-output script-output > delta
+
+  if [[ -s delta ]]; then
+    echo "Wrong output format! See the valid-output & script-output (both have their '\\n' removed)."
+  else
+    rm -f valid-output script-output delta
+    echo "OK"
+  fi
+fi
+
+exit $RET_VAL
+
diff --git a/tests/parameters/#37: -a (on)/cmd-given b/tests/parameters/#37: -a (on)/cmd-given
--- a/tests/parameters/#37: -a (on)/cmd-given
+++ b/tests/parameters/#37: -a (on)/cmd-given
@@ -1,2 +1,48 @@
 #!/bin/bash
-php "$ROOT_PATH"/jsn.php -a < "$ROOT_PATH"/array
+php "$ROOT_PATH"/jsn.php -a < "$ROOT_PATH"/array > script-output
+
+RET_VAL=$?
+
+cat "$ROOT_PATH"/XML-header > valid-output
+
+echo "<root>
+    <array size=\"11\">
+        <item value=\"42\" />
+        <item value=\"69\" />
+        <item value=\"141\" />
+        <item value=\"192\" />
+        <item value=\"256\" />
+        <item value=\"512\" />
+        <item value=\"1024\" />
+        <item value=\"2048\" />
+        <item value=\"8192\" />
+        <item value=\"16384\" />
+        <item value=\"32768\" />
+    </array>
+</root>" >> valid-output
+
+if [[ $RET_VAL -gt 0 ]]; then
+  echo "The script should process this input without any error!"
+else
+  # NOTE: We're injecting <root> & </root> elements so the JExamXML will not
+  #       report an error that the XML is not well-formed.
+  cat "$ROOT_PATH"/XML-header > script-output.tmp
+  echo "<root>" >> script-output.tmp
+  tail -n +2 script-output >> script-output.tmp
+  cat script-output.tmp > script-output
+  echo "</root>" >> script-output
+  
+  rm -f script-output.tmp
+
+  "$ROOT_PATH"/jexamxml.sh "$(pwd)" valid-output script-output
+
+  if [[ $? != 0 ]]; then
+    echo "Wrong output format for -a parameter! See the delta.xml file."
+  else
+    rm -f valid-output script-output delta.xml
+    echo "OK"
+  fi
+fi
+
+exit $RET_VAL
+
diff --git a/tests/parameters/#40: --index-items/cmd-given b/tests/parameters/#40: --index-items/cmd-given
--- a/tests/parameters/#40: --index-items/cmd-given
+++ b/tests/parameters/#40: --index-items/cmd-given
@@ -1,2 +1,47 @@
 #!/bin/bash
-php "$ROOT_PATH"/jsn.php --index-items < "$ROOT_PATH"/array
+php "$ROOT_PATH"/jsn.php --index-items < "$ROOT_PATH"/array > script-output
+
+RET_VAL=$?
+
+cat "$ROOT_PATH"/XML-header > valid-output
+
+echo "<root>
+    <array>
+        <item index=\"1\" value=\"42\" />
+        <item index=\"2\" value=\"69\" />
+        <item index=\"3\" value=\"141\" />
+        <item index=\"4\" value=\"192\" />
+        <item index=\"5\" value=\"256\" />
+        <item index=\"6\" value=\"512\" />
+        <item index=\"7\" value=\"1024\" />
+        <item index=\"8\" value=\"2048\" />
+        <item index=\"9\" value=\"8192\" />
+        <item index=\"10\" value=\"16384\" />
+        <item index=\"11\" value=\"32768\" />
+    </array>
+</root>" >> valid-output
+
+if [[ $RET_VAL -gt 0 ]]; then
+  echo "The script should process this input without any error!"
+else
+  # NOTE: We're injecting <root> & </root> elements so the JExamXML will not
+  #       report an error that the XML is not well-formed.
+  cat "$ROOT_PATH"/XML-header > script-output.tmp
+  echo "<root>" >> script-output.tmp
+  tail -n +2 script-output >> script-output.tmp
+  cat script-output.tmp > script-output
+  echo "</root>" >> script-output
+  
+  rm -f script-output.tmp
+
+  "$ROOT_PATH"/jexamxml.sh "$(pwd)" valid-output script-output
+
+  if [[ $? != 0 ]]; then
+    echo "Wrong output format for --index-items parameter! See the delta.xml file."
+  else
+    rm -f valid-output script-output delta.xml
+    echo "OK"
+  fi
+fi
+
+exit $RET_VAL
diff --git a/tests/parameters/#42: --start=42 (with -t)/cmd-given b/tests/parameters/#42: --start=42 (with -t)/cmd-given
--- a/tests/parameters/#42: --start=42 (with -t)/cmd-given
+++ b/tests/parameters/#42: --start=42 (with -t)/cmd-given
@@ -1,2 +1,47 @@
 #!/bin/bash
-php "$ROOT_PATH"/jsn.php --start=42 -t < "$ROOT_PATH"/array
+php "$ROOT_PATH"/jsn.php --start=42 -t < "$ROOT_PATH"/array > script-output
+
+RET_VAL=$?
+
+cat "$ROOT_PATH"/XML-header > valid-output
+
+echo "<root>
+    <array>
+        <item index=\"42\" value=\"42\" />
+        <item index=\"43\" value=\"69\" />
+        <item index=\"44\" value=\"141\" />
+        <item index=\"45\" value=\"192\" />
+        <item index=\"46\" value=\"256\" />
+        <item index=\"47\" value=\"512\" />
+        <item index=\"48\" value=\"1024\" />
+        <item index=\"49\" value=\"2048\" />
+        <item index=\"50\" value=\"8192\" />
+        <item index=\"51\" value=\"16384\" />
+        <item index=\"52\" value=\"32768\" />
+    </array>
+</root>" >> valid-output
+
+if [[ $RET_VAL -gt 0 ]]; then
+  echo "The script should process this input without any error!"
+else
+  # NOTE: We're injecting <root> & </root> elements so the JExamXML will not
+  #       report an error that the XML is not well-formed.
+  cat "$ROOT_PATH"/XML-header > script-output.tmp
+  echo "<root>" >> script-output.tmp
+  tail -n +2 script-output >> script-output.tmp
+  cat script-output.tmp > script-output
+  echo "</root>" >> script-output
+  
+  rm -f script-output.tmp
+
+  "$ROOT_PATH"/jexamxml.sh "$(pwd)" valid-output script-output
+
+  if [[ $? != 0 ]]; then
+    echo "Wrong output format for --start=42 -t parameters! See the delta.xml file."
+  else
+    rm -f valid-output script-output delta.xml
+    echo "OK"
+  fi
+fi
+
+exit $RET_VAL
diff --git a/tests/parameters/#47: --start=10.99 (with -t)/cmd-given b/tests/parameters/#47: --start=10.99 (with -t)/cmd-given
--- a/tests/parameters/#47: --start=10.99 (with -t)/cmd-given
+++ b/tests/parameters/#47: --start=10.99 (with -t)/cmd-given
@@ -1,2 +1,19 @@
 #!/bin/bash
-php "$ROOT_PATH"/jsn.php --start=10.99 -t < "$ROOT_PATH"/array
+php "$ROOT_PATH"/jsn.php --start=10.99 -t < "$ROOT_PATH"/minimal-json > script-output
+
+RET_VAL=$?
+
+if [[ $RET_VAL -gt 0 ]]; then
+  echo "OK"
+else
+  echo "The script run even when the float value for --start was supplied!"
+fi
+
+if [[ -s script-output ]]; then
+  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
+else
+  rm -f script-output
+fi
+
+exit $RET_VAL
+
diff --git a/tests/parameters/#49: --start=10000000000000000000 -t (INT overflow - MIGHT FAIL)/cmd-given b/tests/parameters/#49: --start=10000000000000000000 -t (INT overflow - MIGHT FAIL)/cmd-given
--- a/tests/parameters/#49: --start=10000000000000000000 -t (INT overflow - MIGHT FAIL)/cmd-given
+++ b/tests/parameters/#49: --start=10000000000000000000 -t (INT overflow - MIGHT FAIL)/cmd-given
@@ -1,2 +1,19 @@
 #!/bin/bash
-php "$ROOT_PATH"/jsn.php --start=10000000000000000000 -t < "$ROOT_PATH"/array
+php "$ROOT_PATH"/jsn.php --start=10000000000000000000 -t < "$ROOT_PATH"/array > script-output
+
+RET_VAL=$?
+
+if [[ $RET_VAL -gt 0 ]]; then
+  echo "OK"
+else
+  echo "The script accepted --start value bigger than INT_MAX value. Is testing for float numbers missing?"
+fi
+
+if [[ -s script-output ]]; then
+  echo "Error message (even HELP) should not be printed to STDOUT in case of error!"
+else
+  rm -f script-output
+fi
+
+exit $RET_VAL
+
