Workaround added to bypass problesm with 'unreadable-file' & 'unwriteable-file'.

diff --git a/tests/initial/#00: Environment/cmd-given b/tests/initial/#00: Environment/cmd-given
--- a/tests/initial/#00: Environment/cmd-given
+++ b/tests/initial/#00: Environment/cmd-given
@@ -5,10 +5,26 @@ if [[ "$ROOT_PATH" == "" ]]; then
   exit 3
 fi
 
-chmod 0000 "$ROOT_PATH/data/parameters/unreadable-file" "$ROOT_PATH/data/parameters/unwriteable-file" || {
-  echo "Could not change rights on testsuite files!"
+
+rm -f "$ROOT_PATH/data/parameters/unreadable-file" || {
+  echo "Could not remove previous 'unreadable-file'"
   exit 4
 }
+
+rm -f "$ROOT_PATH/data/parameters/unwriteable-file" || {
+  echo "Could not remove previous 'unwriteable-file'"
+  exit 4
+}
+
+touch "$ROOT_PATH/data/parameters/unreadable-file"
+touch "$ROOT_PATH/data/parameters/unwriteable-file"
+
+
+chmod 0000 "$ROOT_PATH/data/parameters/unreadable-file" "$ROOT_PATH/data/parameters/unwriteable-file" || {
+  echo "Could not change rights on testsuite files!"
+  exit 5
+}
+
 
 if [[ "$(hostname)" == "merlin.fit.vutbr.cz" ]]; then
   typeset IFS_backup=$IFS           # Backup of actual IFS for later restoration.
@@ -16,7 +32,7 @@ if [[ "$(hostname)" == "merlin.fit.vutbr.cz" ]]; then
 
   cd ../../ || {
     echo "Script could not change into tests directory!"
-    exit 5
+    exit 6
   }
 
   for file_path in $(find . -type f -name cmd-given | sort); do
@@ -33,24 +49,27 @@ else
 
   if [[ $? != 0 ]]; then
     echo "The PHP CLI is probably not installed! Please, double-check it and try again!"
-    exit 6
+    exit 7
   fi
 fi
 
-chmod +x "$ROOT_PATH"/jexamxml.sh
 
+chmod +x "$ROOT_PATH"/jexamxml.sh
 "$ROOT_PATH"/jexamxml.sh "$(pwd)" "" ""
+
 
 if [[ $? != 2 ]]; then
   echo "The Java CLI is either missing or JExamXML files are corrupted!"
-  exit 5
+  exit 8
 fi
 
 if ! [[ -r "$ROOT_PATH/jsn.php" && -f "$ROOT_PATH/jsn.php" && -s "$ROOT_PATH/jsn.php" ]]; then
   echo "The 'jsn.php' is not present in '\$ROOT_PATH' or is not readable!"
-  exit 6
+  exit 9
 fi
 
+
 echo "OK"
+
 
 exit 0
